### ISSUE TITLE
let github_token be the option of the plugin

### ISSUE THREAD

**Issue by yegor256** [zerocracy/pages-action#134]
Now, we have to do this:

```
- uses: zerocracy/pages-action@0.0.35
  with:
    factbase: foo.fb
    verbose: true
    output: my-directory
    columns: who,when,repository
    hidden: _id,_time
    options: |
      github_token=${{ secrets.GITHUB_TOKEN }}
```

Let's make it possible to do this:

```
- uses: zerocracy/pages-action@0.0.35
  with:
    factbase: foo.fb
    verbose: true
    output: my-directory
    columns: who,when,repository
    hidden: _id,_time
    github_token: ${{ secrets.GITHUB_TOKEN }}
```
