### ISSUE TITLE
the `palette` option

### ISSUE THREAD

**Issue by yegor256** [zerocracy/pages-action#31]
Let's make it possible to configure the palette of the output. Now, we can only configure the logo, but would be great to do this: 

```
      - uses: zerocracy/pages-action@0.0.16
        with:
          palette: dark
          factbase: foo.fb
```

Here, the `dark` means that the entire page should be rendered in a dark style. Would be great to have: `classic`, `dark`, and maybe `mild` options.
